// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://molxbyytnuzfhcjmirms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vbHhieXl0bnV6Zmhjam1pcm1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTkwOTEsImV4cCI6MjA2NTYzNTA5MX0.2B1_2b32KUCPQpf7vZe3NjgcejWvEdm5468A5rDnyiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);